package com.cryptocenter.andrey.owlsight.utils;

public enum Screen {
    ADD_CAMERA, CHOOSE_GROUP, GROUPS, MENU, MONITOR, PROFILE, REGISTER, REGISTER_SMS, SIGN_IN, SINGLE_PLAYER, STREAM, VIDEO_FROM_DATE,
    CHANGE_PHONE, LEAVE_ACCOUNT, CHANGE_PASSWORD
}
